# Generated by Django 5.2.8 on 2025-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
