# Generated by Django 5.2.8 on 2025-11-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
