# Generated by Django 5.2.8 on 2025-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0004_driverlocation_current_ride_ride_actual_dropoff_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('premium', 'Premium'), ('xl', 'XL'), ('boda', 'Boda')], default='economy', max_length=20),
        ),
    ]
