# Generated by Django 5.2.8 on 2025-11-18 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0006_customerpaymentmethod_customerchathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_new_driver_notifications', models.BooleanField(default=True)),
                ('receive_emergency_notifications', models.BooleanField(default=True)),
                ('receive_ride_issue_notifications', models.BooleanField(default=True)),
                ('receive_system_alerts', models.BooleanField(default=True)),
                ('receive_payment_issues', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('minimum_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_driver', 'New Driver Registration'), ('new_emergency', 'New Emergency Request'), ('ride_issue', 'Ride Issue Reported'), ('system_alert', 'System Alert'), ('payment_issue', 'Payment Issue'), ('driver_suspended', 'Driver Suspended')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_emergency_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ryde_app.emergencyrequest')),
                ('related_ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ryde_app.ride')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='ryde_app_ad_is_read_7f8718_idx'), models.Index(fields=['notification_type', 'created_at'], name='ryde_app_ad_notific_e180b1_idx')],
            },
        ),
    ]
