# Generated by Django 5.2.8 on 2025-11-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0007_notificationpreference_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_license_file',
            field=models.FileField(blank=True, help_text='Upload a clear photo of your valid driving license', null=True, upload_to='driver_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='logbook_file',
            field=models.FileField(blank=True, help_text='Upload a clear photo of your vehicle logbook', null=True, upload_to='driver_documents/logbooks/'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_file',
            field=models.FileField(blank=True, help_text='Upload a clear photo of your national ID', null=True, upload_to='driver_documents/national_ids/'),
        ),
    ]
