# Generated by Django 5.2.8 on 2025-11-20 08:04

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0008_user_driver_license_file_user_logbook_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_license_file',
            field=models.FileField(blank=True, help_text='Upload a clear photo of your valid driving license', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='driver_documents/licenses/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logbook_file',
            field=models.FileField(blank=True, help_text='Upload a clear photo of your vehicle logbook', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='driver_documents/logbooks/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id_file',
            field=models.FileField(blank=True, help_text='Upload a clear photo of your national ID', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='driver_documents/national_ids/'),
        ),
    ]
