# Generated by Django 5.2.8 on 2025-11-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0009_alter_user_driver_license_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='package_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='package_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='service_type',
            field=models.CharField(choices=[('ride', 'Ride'), ('package', 'Package Delivery'), ('food', 'Food Delivery'), ('document', 'Document Courier')], default='ride', max_length=20),
        ),
    ]
