# Generated by Django 5.2.8 on 2025-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryde_app', '0012_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('driving_to_destination', 'Driving to Destination'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=30),
        ),
    ]
